package com.crm1.entity;
// Generated Mar 17, 2018 1:58:45 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Controle generated by hbm2java
 */
@Entity
@Table(name="controle"
    ,catalog="crm"
)
public class Controle  implements java.io.Serializable {


     private Integer idControle;
     private PvIntervention pvIntervention;
     private String demande;
     private String conformite;
     private String obserSpec;

    public Controle() {
    }

    public Controle(PvIntervention pvIntervention, String demande, String conformite, String obserSpec) {
       this.pvIntervention = pvIntervention;
       this.demande = demande;
       this.conformite = conformite;
       this.obserSpec = obserSpec;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_controle", unique=true, nullable=false)
    public Integer getIdControle() {
        return this.idControle;
    }
    
    public void setIdControle(Integer idControle) {
        this.idControle = idControle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_pv", nullable=false)
    public PvIntervention getPvIntervention() {
        return this.pvIntervention;
    }
    
    public void setPvIntervention(PvIntervention pvIntervention) {
        this.pvIntervention = pvIntervention;
    }

    
    @Column(name="demande", nullable=false, length=100)
    public String getDemande() {
        return this.demande;
    }
    
    public void setDemande(String demande) {
        this.demande = demande;
    }

    
    @Column(name="Conformite", nullable=false, length=100)
    public String getConformite() {
        return this.conformite;
    }
    
    public void setConformite(String conformite) {
        this.conformite = conformite;
    }

    
    @Column(name="Obser_spec", nullable=false, length=100)
    public String getObserSpec() {
        return this.obserSpec;
    }
    
    public void setObserSpec(String obserSpec) {
        this.obserSpec = obserSpec;
    }




}


