package com.crm1.entity;
// Generated Mar 30, 2018 5:12:53 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="contact"
    ,catalog="crm"
    , uniqueConstraints = @UniqueConstraint(columnNames="tel") 
)
public class Contact  implements java.io.Serializable {


     private Integer idContact;
     private Client client;
     private String tel;
     private String email;
     private String fax;

    public Contact() {
    }

    public Contact(Client client, String tel, String email, String fax) {
       this.client = client;
       this.tel = tel;
       this.email = email;
       this.fax = fax;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_contact", unique=true, nullable=false)
    public Integer getIdContact() {
        return this.idContact;
    }
    
    public void setIdContact(Integer idContact) {
        this.idContact = idContact;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_cli", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    
    @Column(name="tel", unique=true, nullable=false, length=20)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="email", nullable=false, length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="fax", nullable=false, length=20)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }




}


