package com.crm1.entity;
// Generated Mar 17, 2018 1:58:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Devis generated by hbm2java
 */
@Entity
@Table(name="devis"
    ,catalog="crm"
)
public class Devis  implements java.io.Serializable {


     private Integer idDevis;
     private Date dateCreaD;
     private String observ;
     private BigDecimal THt;
     private BigDecimal TRemise;
     private BigDecimal TTva;
     private BigDecimal ttc;
     private BigDecimal timbre;
     private BigDecimal netPayer;
     private Set<LigneDevis> ligneDevises = new HashSet<LigneDevis>(0);

    public Devis() {
    }

	
    public Devis(Date dateCreaD, String observ, BigDecimal THt, BigDecimal TRemise, BigDecimal TTva, BigDecimal ttc, BigDecimal timbre, BigDecimal netPayer) {
        this.dateCreaD = dateCreaD;
        this.observ = observ;
        this.THt = THt;
        this.TRemise = TRemise;
        this.TTva = TTva;
        this.ttc = ttc;
        this.timbre = timbre;
        this.netPayer = netPayer;
    }
    public Devis(Date dateCreaD, String observ, BigDecimal THt, BigDecimal TRemise, BigDecimal TTva, BigDecimal ttc, BigDecimal timbre, BigDecimal netPayer, Set<LigneDevis> ligneDevises) {
       this.dateCreaD = dateCreaD;
       this.observ = observ;
       this.THt = THt;
       this.TRemise = TRemise;
       this.TTva = TTva;
       this.ttc = ttc;
       this.timbre = timbre;
       this.netPayer = netPayer;
       this.ligneDevises = ligneDevises;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_devis", unique=true, nullable=false)
    public Integer getIdDevis() {
        return this.idDevis;
    }
    
    public void setIdDevis(Integer idDevis) {
        this.idDevis = idDevis;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_crea_d", nullable=false, length=10)
    public Date getDateCreaD() {
        return this.dateCreaD;
    }
    
    public void setDateCreaD(Date dateCreaD) {
        this.dateCreaD = dateCreaD;
    }

    
    @Column(name="Observ", nullable=false)
    public String getObserv() {
        return this.observ;
    }
    
    public void setObserv(String observ) {
        this.observ = observ;
    }

    
    @Column(name="T_ht", nullable=false, precision=8, scale=3)
    public BigDecimal getTHt() {
        return this.THt;
    }
    
    public void setTHt(BigDecimal THt) {
        this.THt = THt;
    }

    
    @Column(name="T_remise", nullable=false, precision=8, scale=3)
    public BigDecimal getTRemise() {
        return this.TRemise;
    }
    
    public void setTRemise(BigDecimal TRemise) {
        this.TRemise = TRemise;
    }

    
    @Column(name="T_tva", nullable=false, precision=8, scale=3)
    public BigDecimal getTTva() {
        return this.TTva;
    }
    
    public void setTTva(BigDecimal TTva) {
        this.TTva = TTva;
    }

    
    @Column(name="Ttc", nullable=false, precision=8, scale=3)
    public BigDecimal getTtc() {
        return this.ttc;
    }
    
    public void setTtc(BigDecimal ttc) {
        this.ttc = ttc;
    }

    
    @Column(name="Timbre", nullable=false, precision=8, scale=3)
    public BigDecimal getTimbre() {
        return this.timbre;
    }
    
    public void setTimbre(BigDecimal timbre) {
        this.timbre = timbre;
    }

    
    @Column(name="Net_payer", nullable=false, precision=8, scale=3)
    public BigDecimal getNetPayer() {
        return this.netPayer;
    }
    
    public void setNetPayer(BigDecimal netPayer) {
        this.netPayer = netPayer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="devis")
    public Set<LigneDevis> getLigneDevises() {
        return this.ligneDevises;
    }
    
    public void setLigneDevises(Set<LigneDevis> ligneDevises) {
        this.ligneDevises = ligneDevises;
    }




}


