package com.crm1.entity;
// Generated Mar 17, 2018 1:58:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name="facture"
    ,catalog="crm"
)
public class Facture  implements java.io.Serializable {


     private int idFacture;
     private BonCommande bonCommande;
     private Date dateCreaF;
     private String observ;
     private BigDecimal THt;
     private BigDecimal TRemise;
     private BigDecimal TTva;
     private BigDecimal ttc;
     private BigDecimal timbre;
     private BigDecimal netPayer;
     private String modePaie;
     private int delaiPaie;

    public Facture() {
    }

    public Facture(int idFacture, BonCommande bonCommande, Date dateCreaF, String observ, BigDecimal THt, BigDecimal TRemise, BigDecimal TTva, BigDecimal ttc, BigDecimal timbre, BigDecimal netPayer, String modePaie, int delaiPaie) {
       this.idFacture = idFacture;
       this.bonCommande = bonCommande;
       this.dateCreaF = dateCreaF;
       this.observ = observ;
       this.THt = THt;
       this.TRemise = TRemise;
       this.TTva = TTva;
       this.ttc = ttc;
       this.timbre = timbre;
       this.netPayer = netPayer;
       this.modePaie = modePaie;
       this.delaiPaie = delaiPaie;
    }
   
     @Id 

    
    @Column(name="Id_facture", unique=true, nullable=false)
    public int getIdFacture() {
        return this.idFacture;
    }
    
    public void setIdFacture(int idFacture) {
        this.idFacture = idFacture;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_cmd", nullable=false)
    public BonCommande getBonCommande() {
        return this.bonCommande;
    }
    
    public void setBonCommande(BonCommande bonCommande) {
        this.bonCommande = bonCommande;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_crea_f", nullable=false, length=10)
    public Date getDateCreaF() {
        return this.dateCreaF;
    }
    
    public void setDateCreaF(Date dateCreaF) {
        this.dateCreaF = dateCreaF;
    }

    
    @Column(name="observ", nullable=false)
    public String getObserv() {
        return this.observ;
    }
    
    public void setObserv(String observ) {
        this.observ = observ;
    }

    
    @Column(name="T_HT", nullable=false, precision=8, scale=3)
    public BigDecimal getTHt() {
        return this.THt;
    }
    
    public void setTHt(BigDecimal THt) {
        this.THt = THt;
    }

    
    @Column(name="T_Remise", nullable=false, precision=8, scale=3)
    public BigDecimal getTRemise() {
        return this.TRemise;
    }
    
    public void setTRemise(BigDecimal TRemise) {
        this.TRemise = TRemise;
    }

    
    @Column(name="T_TVA", nullable=false, precision=8, scale=3)
    public BigDecimal getTTva() {
        return this.TTva;
    }
    
    public void setTTva(BigDecimal TTva) {
        this.TTva = TTva;
    }

    
    @Column(name="TTC", nullable=false, precision=8, scale=3)
    public BigDecimal getTtc() {
        return this.ttc;
    }
    
    public void setTtc(BigDecimal ttc) {
        this.ttc = ttc;
    }

    
    @Column(name="Timbre", nullable=false, precision=8, scale=3)
    public BigDecimal getTimbre() {
        return this.timbre;
    }
    
    public void setTimbre(BigDecimal timbre) {
        this.timbre = timbre;
    }

    
    @Column(name="net_payer", nullable=false, precision=8, scale=3)
    public BigDecimal getNetPayer() {
        return this.netPayer;
    }
    
    public void setNetPayer(BigDecimal netPayer) {
        this.netPayer = netPayer;
    }

    
    @Column(name="mode_paie", nullable=false, length=30)
    public String getModePaie() {
        return this.modePaie;
    }
    
    public void setModePaie(String modePaie) {
        this.modePaie = modePaie;
    }

    
    @Column(name="delai_paie", nullable=false)
    public int getDelaiPaie() {
        return this.delaiPaie;
    }
    
    public void setDelaiPaie(int delaiPaie) {
        this.delaiPaie = delaiPaie;
    }




}


