package com.crm1.entity;
// Generated Mar 30, 2018 5:12:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FicheSuivi generated by hbm2java
 */
@Entity
@Table(name="fiche_suivi"
    ,catalog="crm"
)
public class FicheSuivi  implements java.io.Serializable {


     private Integer idFiche;
     private PvIntervention pvIntervention;
     private Date dateInterv;
     private String typeJour;
     private Date heureArrivee;
     private Date heureDepart;
     private String periode;
     private String travaux;

    public FicheSuivi() {
    }

    public FicheSuivi(PvIntervention pvIntervention, Date dateInterv, String typeJour, Date heureArrivee, Date heureDepart, String periode, String travaux) {
       this.pvIntervention = pvIntervention;
       this.dateInterv = dateInterv;
       this.typeJour = typeJour;
       this.heureArrivee = heureArrivee;
       this.heureDepart = heureDepart;
       this.periode = periode;
       this.travaux = travaux;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_fiche", unique=true, nullable=false)
    public Integer getIdFiche() {
        return this.idFiche;
    }
    
    public void setIdFiche(Integer idFiche) {
        this.idFiche = idFiche;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pv", nullable=false)
    public PvIntervention getPvIntervention() {
        return this.pvIntervention;
    }
    
    public void setPvIntervention(PvIntervention pvIntervention) {
        this.pvIntervention = pvIntervention;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_interv", nullable=false, length=10)
    public Date getDateInterv() {
        return this.dateInterv;
    }
    
    public void setDateInterv(Date dateInterv) {
        this.dateInterv = dateInterv;
    }

    
    @Column(name="Type_jour", nullable=false, length=6)
    public String getTypeJour() {
        return this.typeJour;
    }
    
    public void setTypeJour(String typeJour) {
        this.typeJour = typeJour;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="Heure_arrivee", nullable=false, length=8)
    public Date getHeureArrivee() {
        return this.heureArrivee;
    }
    
    public void setHeureArrivee(Date heureArrivee) {
        this.heureArrivee = heureArrivee;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="Heure_depart", nullable=false, length=8)
    public Date getHeureDepart() {
        return this.heureDepart;
    }
    
    public void setHeureDepart(Date heureDepart) {
        this.heureDepart = heureDepart;
    }

    
    @Column(name="periode", nullable=false, length=10)
    public String getPeriode() {
        return this.periode;
    }
    
    public void setPeriode(String periode) {
        this.periode = periode;
    }

    
    @Column(name="travaux", nullable=false)
    public String getTravaux() {
        return this.travaux;
    }
    
    public void setTravaux(String travaux) {
        this.travaux = travaux;
    }




}


