package com.crm1.entity;
// Generated Mar 17, 2018 1:58:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ligne generated by hbm2java
 */
@Entity
@Table(name="ligne"
    ,catalog="crm"
)
public class Ligne  implements java.io.Serializable {


     private int idLigne;
     private BonCommande bonCommande;
     private String libelle;
     private int quantite;
     private BigDecimal puHt;
     private BigDecimal remise;
     private BigDecimal ptht;
     private BigDecimal tva;
     private BigDecimal puTtc;
     private int idRec;

    public Ligne() {
    }

    public Ligne(int idLigne, BonCommande bonCommande, String libelle, int quantite, BigDecimal puHt, BigDecimal remise, BigDecimal ptht, BigDecimal tva, BigDecimal puTtc, int idRec) {
       this.idLigne = idLigne;
       this.bonCommande = bonCommande;
       this.libelle = libelle;
       this.quantite = quantite;
       this.puHt = puHt;
       this.remise = remise;
       this.ptht = ptht;
       this.tva = tva;
       this.puTtc = puTtc;
       this.idRec = idRec;
    }
   
     @Id 

    
    @Column(name="Id_Ligne", unique=true, nullable=false)
    public int getIdLigne() {
        return this.idLigne;
    }
    
    public void setIdLigne(int idLigne) {
        this.idLigne = idLigne;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_cmd", nullable=false)
    public BonCommande getBonCommande() {
        return this.bonCommande;
    }
    
    public void setBonCommande(BonCommande bonCommande) {
        this.bonCommande = bonCommande;
    }

    
    @Column(name="libelle", nullable=false, length=30)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="quantite", nullable=false)
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }

    
    @Column(name="PU_HT", nullable=false, precision=8, scale=3)
    public BigDecimal getPuHt() {
        return this.puHt;
    }
    
    public void setPuHt(BigDecimal puHt) {
        this.puHt = puHt;
    }

    
    @Column(name="remise", nullable=false, precision=8, scale=3)
    public BigDecimal getRemise() {
        return this.remise;
    }
    
    public void setRemise(BigDecimal remise) {
        this.remise = remise;
    }

    
    @Column(name="PTHT", nullable=false, precision=8, scale=3)
    public BigDecimal getPtht() {
        return this.ptht;
    }
    
    public void setPtht(BigDecimal ptht) {
        this.ptht = ptht;
    }

    
    @Column(name="TVA", nullable=false, precision=8, scale=3)
    public BigDecimal getTva() {
        return this.tva;
    }
    
    public void setTva(BigDecimal tva) {
        this.tva = tva;
    }

    
    @Column(name="PU_TTC", nullable=false, precision=8, scale=3)
    public BigDecimal getPuTtc() {
        return this.puTtc;
    }
    
    public void setPuTtc(BigDecimal puTtc) {
        this.puTtc = puTtc;
    }

    
    @Column(name="Id_rec", nullable=false)
    public int getIdRec() {
        return this.idRec;
    }
    
    public void setIdRec(int idRec) {
        this.idRec = idRec;
    }




}


