package com.crm1.entity;
// Generated Apr 20, 2018 2:07:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LigneDevis generated by hbm2java
 */
@Entity
@Table(name="ligne_devis"
    ,catalog="crm"
)
public class LigneDevis  implements java.io.Serializable {


     private Integer idLigne;
     private Devis devis;
     private Reclamation reclamation;
     private String libelle;
     private int quantite;
     private BigDecimal puHt;
     private BigDecimal remise;
     private BigDecimal ptHt;
     private BigDecimal tva;
     private BigDecimal puTtc;

    public LigneDevis() {
    }

    public LigneDevis(Devis devis, Reclamation reclamation, String libelle, int quantite, BigDecimal puHt, BigDecimal remise, BigDecimal ptHt, BigDecimal tva, BigDecimal puTtc) {
       this.devis = devis;
       this.reclamation = reclamation;
       this.libelle = libelle;
       this.quantite = quantite;
       this.puHt = puHt;
       this.remise = remise;
       this.ptHt = ptHt;
       this.tva = tva;
       this.puTtc = puTtc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_ligne", unique=true, nullable=false)
    public Integer getIdLigne() {
        return this.idLigne;
    }
    
    public void setIdLigne(Integer idLigne) {
        this.idLigne = idLigne;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_devis", nullable=false)
    public Devis getDevis() {
        return this.devis;
    }
    
    public void setDevis(Devis devis) {
        this.devis = devis;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_rec", nullable=false)
    public Reclamation getReclamation() {
        return this.reclamation;
    }
    
    public void setReclamation(Reclamation reclamation) {
        this.reclamation = reclamation;
    }

    
    @Column(name="Libelle", nullable=false, length=30)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="quantite", nullable=false)
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }

    
    @Column(name="pu_ht", nullable=false, precision=8, scale=3)
    public BigDecimal getPuHt() {
        return this.puHt;
    }
    
    public void setPuHt(BigDecimal puHt) {
        this.puHt = puHt;
    }

    
    @Column(name="remise", nullable=false, precision=8, scale=3)
    public BigDecimal getRemise() {
        return this.remise;
    }
    
    public void setRemise(BigDecimal remise) {
        this.remise = remise;
    }

    
    @Column(name="Pt_ht", nullable=false, precision=8, scale=3)
    public BigDecimal getPtHt() {
        return this.ptHt;
    }
    
    public void setPtHt(BigDecimal ptHt) {
        this.ptHt = ptHt;
    }

    
    @Column(name="tva", nullable=false, precision=8, scale=3)
    public BigDecimal getTva() {
        return this.tva;
    }
    
    public void setTva(BigDecimal tva) {
        this.tva = tva;
    }

    
    @Column(name="Pu_ttc", nullable=false, precision=8, scale=3)
    public BigDecimal getPuTtc() {
        return this.puTtc;
    }
    
    public void setPuTtc(BigDecimal puTtc) {
        this.puTtc = puTtc;
    }




}


