package com.crm1.entity;
// Generated Mar 17, 2018 1:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Personnel generated by hbm2java
 */
@Entity
@Table(name="personnel"
    ,catalog="crm"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cin"), @UniqueConstraint(columnNames="cnrps"), @UniqueConstraint(columnNames="tel")} 
)
public class Personnel  implements java.io.Serializable {


     private Integer idPers;
     private String cnrps;
     private String cin;
     private int nomPers;
     private int prenomPers;
     private int loginPers;
     private int pwdPers;
     private Date dateNais;
     private String sexe;
     private String etatCivil;
     private Date nat;
     private int dateEmbauche;
     private String tel;
     private String email;
     private String superieur;
     private String grade;
     private Set<Affectation> affectations = new HashSet<Affectation>(0);

    public Personnel() {
    }

	
    public Personnel(String cnrps, String cin, int nomPers, int prenomPers, int loginPers, int pwdPers, Date dateNais, String sexe, String etatCivil, Date nat, int dateEmbauche, String tel, String email, String superieur, String grade) {
        this.cnrps = cnrps;
        this.cin = cin;
        this.nomPers = nomPers;
        this.prenomPers = prenomPers;
        this.loginPers = loginPers;
        this.pwdPers = pwdPers;
        this.dateNais = dateNais;
        this.sexe = sexe;
        this.etatCivil = etatCivil;
        this.nat = nat;
        this.dateEmbauche = dateEmbauche;
        this.tel = tel;
        this.email = email;
        this.superieur = superieur;
        this.grade = grade;
    }
    public Personnel(String cnrps, String cin, int nomPers, int prenomPers, int loginPers, int pwdPers, Date dateNais, String sexe, String etatCivil, Date nat, int dateEmbauche, String tel, String email, String superieur, String grade, Set<Affectation> affectations) {
       this.cnrps = cnrps;
       this.cin = cin;
       this.nomPers = nomPers;
       this.prenomPers = prenomPers;
       this.loginPers = loginPers;
       this.pwdPers = pwdPers;
       this.dateNais = dateNais;
       this.sexe = sexe;
       this.etatCivil = etatCivil;
       this.nat = nat;
       this.dateEmbauche = dateEmbauche;
       this.tel = tel;
       this.email = email;
       this.superieur = superieur;
       this.grade = grade;
       this.affectations = affectations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_pers", unique=true, nullable=false)
    public Integer getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(Integer idPers) {
        this.idPers = idPers;
    }

    
    @Column(name="cnrps", unique=true, nullable=false, length=12)
    public String getCnrps() {
        return this.cnrps;
    }
    
    public void setCnrps(String cnrps) {
        this.cnrps = cnrps;
    }

    
    @Column(name="cin", unique=true, nullable=false, length=8)
    public String getCin() {
        return this.cin;
    }
    
    public void setCin(String cin) {
        this.cin = cin;
    }

    
    @Column(name="nom_pers", nullable=false)
    public int getNomPers() {
        return this.nomPers;
    }
    
    public void setNomPers(int nomPers) {
        this.nomPers = nomPers;
    }

    
    @Column(name="prenom_pers", nullable=false)
    public int getPrenomPers() {
        return this.prenomPers;
    }
    
    public void setPrenomPers(int prenomPers) {
        this.prenomPers = prenomPers;
    }

    
    @Column(name="Login_pers", nullable=false)
    public int getLoginPers() {
        return this.loginPers;
    }
    
    public void setLoginPers(int loginPers) {
        this.loginPers = loginPers;
    }

    
    @Column(name="Pwd_pers", nullable=false)
    public int getPwdPers() {
        return this.pwdPers;
    }
    
    public void setPwdPers(int pwdPers) {
        this.pwdPers = pwdPers;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_nais", nullable=false, length=10)
    public Date getDateNais() {
        return this.dateNais;
    }
    
    public void setDateNais(Date dateNais) {
        this.dateNais = dateNais;
    }

    
    @Column(name="sexe", nullable=false, length=9)
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    
    @Column(name="etat_civil", nullable=false, length=12)
    public String getEtatCivil() {
        return this.etatCivil;
    }
    
    public void setEtatCivil(String etatCivil) {
        this.etatCivil = etatCivil;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nat", nullable=false, length=10)
    public Date getNat() {
        return this.nat;
    }
    
    public void setNat(Date nat) {
        this.nat = nat;
    }

    
    @Column(name="date_embauche", nullable=false)
    public int getDateEmbauche() {
        return this.dateEmbauche;
    }
    
    public void setDateEmbauche(int dateEmbauche) {
        this.dateEmbauche = dateEmbauche;
    }

    
    @Column(name="tel", unique=true, nullable=false, length=20)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="email", nullable=false, length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="superieur", nullable=false, length=12)
    public String getSuperieur() {
        return this.superieur;
    }
    
    public void setSuperieur(String superieur) {
        this.superieur = superieur;
    }

    
    @Column(name="grade", nullable=false, length=30)
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personnel")
    public Set<Affectation> getAffectations() {
        return this.affectations;
    }
    
    public void setAffectations(Set<Affectation> affectations) {
        this.affectations = affectations;
    }




}


