package com.crm1.entity;
// Generated Apr 20, 2018 2:07:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PvIntervention generated by hbm2java
 */
@Entity
@Table(name="pv_intervention"
    ,catalog="crm"
)
public class PvIntervention  implements java.io.Serializable {


     private Integer idPv;
     private Reclamation reclamation;
     private String observGen;
     private Set<Controle> controles = new HashSet<Controle>(0);
     private Set<FicheSuivi> ficheSuivis = new HashSet<FicheSuivi>(0);
     private Set<SelectService> selectServices = new HashSet<SelectService>(0);

    public PvIntervention() {
    }

	
    public PvIntervention(Reclamation reclamation, String observGen) {
        this.reclamation = reclamation;
        this.observGen = observGen;
    }
    public PvIntervention(Reclamation reclamation, String observGen, Set<Controle> controles, Set<FicheSuivi> ficheSuivis, Set<SelectService> selectServices) {
       this.reclamation = reclamation;
       this.observGen = observGen;
       this.controles = controles;
       this.ficheSuivis = ficheSuivis;
       this.selectServices = selectServices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_pv", unique=true, nullable=false)
    public Integer getIdPv() {
        return this.idPv;
    }
    
    public void setIdPv(Integer idPv) {
        this.idPv = idPv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_rec", nullable=false)
    public Reclamation getReclamation() {
        return this.reclamation;
    }
    
    public void setReclamation(Reclamation reclamation) {
        this.reclamation = reclamation;
    }

    
    @Column(name="Observ_gen", nullable=false)
    public String getObservGen() {
        return this.observGen;
    }
    
    public void setObservGen(String observGen) {
        this.observGen = observGen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pvIntervention")
    public Set<Controle> getControles() {
        return this.controles;
    }
    
    public void setControles(Set<Controle> controles) {
        this.controles = controles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pvIntervention")
    public Set<FicheSuivi> getFicheSuivis() {
        return this.ficheSuivis;
    }
    
    public void setFicheSuivis(Set<FicheSuivi> ficheSuivis) {
        this.ficheSuivis = ficheSuivis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pvIntervention")
    public Set<SelectService> getSelectServices() {
        return this.selectServices;
    }
    
    public void setSelectServices(Set<SelectService> selectServices) {
        this.selectServices = selectServices;
    }




}


