package com.crm1.entity;
// Generated Mar 30, 2018 5:12:53 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SelectService generated by hbm2java
 */
@Entity
@Table(name="select_service"
    ,catalog="crm"
)
public class SelectService  implements java.io.Serializable {


     private SelectServiceId id;
     private PvIntervention pvIntervention;
     private Service service;
     private String autre;

    public SelectService() {
    }

    public SelectService(SelectServiceId id, PvIntervention pvIntervention, Service service, String autre) {
       this.id = id;
       this.pvIntervention = pvIntervention;
       this.service = service;
       this.autre = autre;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPv", column=@Column(name="Id_pv", nullable=false) ), 
        @AttributeOverride(name="idServ", column=@Column(name="id_serv", nullable=false) ) } )
    public SelectServiceId getId() {
        return this.id;
    }
    
    public void setId(SelectServiceId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_pv", nullable=false, insertable=false, updatable=false)
    public PvIntervention getPvIntervention() {
        return this.pvIntervention;
    }
    
    public void setPvIntervention(PvIntervention pvIntervention) {
        this.pvIntervention = pvIntervention;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_serv", nullable=false, insertable=false, updatable=false)
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }

    
    @Column(name="autre", nullable=false, length=50)
    public String getAutre() {
        return this.autre;
    }
    
    public void setAutre(String autre) {
        this.autre = autre;
    }




}


