package com.crm1.entity;
// Generated Apr 20, 2018 2:07:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SelectServiceId generated by hbm2java
 */
@Embeddable
public class SelectServiceId  implements java.io.Serializable {


     private int idPv;
     private int idServ;

    public SelectServiceId() {
    }

    public SelectServiceId(int idPv, int idServ) {
       this.idPv = idPv;
       this.idServ = idServ;
    }
   


    @Column(name="Id_pv", nullable=false)
    public int getIdPv() {
        return this.idPv;
    }
    
    public void setIdPv(int idPv) {
        this.idPv = idPv;
    }


    @Column(name="id_serv", nullable=false)
    public int getIdServ() {
        return this.idServ;
    }
    
    public void setIdServ(int idServ) {
        this.idServ = idServ;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SelectServiceId) ) return false;
		 SelectServiceId castOther = ( SelectServiceId ) other; 
         
		 return (this.getIdPv()==castOther.getIdPv())
 && (this.getIdServ()==castOther.getIdServ());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPv();
         result = 37 * result + this.getIdServ();
         return result;
   }   


}


