package com.crm1.entity;
// Generated Mar 17, 2018 1:58:45 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SelectActiviteId generated by hbm2java
 */
@Embeddable
public class SelectActiviteId  implements java.io.Serializable {


     private int idCli;
     private int idAct;

    public SelectActiviteId() {
    }

    public SelectActiviteId(int idCli, int idAct) {
       this.idCli = idCli;
       this.idAct = idAct;
    }
   


    @Column(name="id_cli", nullable=false)
    public int getIdCli() {
        return this.idCli;
    }
    
    public void setIdCli(int idCli) {
        this.idCli = idCli;
    }


    @Column(name="id_act", nullable=false)
    public int getIdAct() {
        return this.idAct;
    }
    
    public void setIdAct(int idAct) {
        this.idAct = idAct;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SelectActiviteId) ) return false;
		 SelectActiviteId castOther = ( SelectActiviteId ) other; 
         
		 return (this.getIdCli()==castOther.getIdCli())
 && (this.getIdAct()==castOther.getIdAct());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCli();
         result = 37 * result + this.getIdAct();
         return result;
   }   


}


