package com.crm1.entity;
// Generated Apr 20, 2018 2:07:18 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SelectActivite generated by hbm2java
 */
@Entity
@Table(name="select_activite"
    ,catalog="crm"
)
public class SelectActivite  implements java.io.Serializable {


     private SelectActiviteId id;
     private Activite activite;
     private Client client;
     private String dexAct;

    public SelectActivite() {
    }

    public SelectActivite(SelectActiviteId id, Activite activite, Client client, String dexAct) {
       this.id = id;
       this.activite = activite;
       this.client = client;
       this.dexAct = dexAct;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCli", column=@Column(name="id_cli", nullable=false) ), 
        @AttributeOverride(name="idAct", column=@Column(name="id_act", nullable=false) ) } )
    public SelectActiviteId getId() {
        return this.id;
    }
    
    public void setId(SelectActiviteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cli", nullable=false, insertable=false, updatable=false)
    public Activite getActivite() {
        return this.activite;
    }
    
    public void setActivite(Activite activite) {
        this.activite = activite;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cli", nullable=false, insertable=false, updatable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    
    @Column(name="dex_act", nullable=false, length=50)
    public String getDexAct() {
        return this.dexAct;
    }
    
    public void setDexAct(String dexAct) {
        this.dexAct = dexAct;
    }




}


